# Site metadata
title: "ARIS Lab"
description: "Applied Recommendation and Information Systems Lab @ Kookmin University"
baseurl: ""  # 루트 도메인 사용 시 공백
url: "https://aris.github.io"  # 사용자의 GitHub Pages 주소
email: "hongkyun@kookmin.ac.kr"

# Owner information
author:
  name: "Hong-Kyun Bae"
  position: "Assistant Professor"
  affiliation: "Kookmin University"
  email: "hongkyun@kookmin.ac.kr"

# Navigation links
navigation:
  - title: "Home"
    url: "/"
  - title: "Professor"
    url: "/about.html"
  - title: "Members"
    url: "/people.html"
  - title: "Research"
    url: "/projects.html"
  - title: "Contact"
    url: "/contact.html"

# Social (선택사항)
github_username: hongkyun

# SEO and Localization
lang: "en"
timezone: "Asia/Seoul"

# Theme and markdown options
markdown: kramdown
highlighter: rouge
